In [1]:
import pandas as pd
import os
import numpy as np
import yfinance as yf
import torch
# import torch_geometric
import sklearn

In [2]:
stocks = [
    "RELIANCE.NS",
    "TCS.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "INFY.NS",
    "HINDUNILVR.NS",
    "ITC.NS",
    "SBIN.NS",
    "BHARTIARTL.NS",
    "KOTAKBANK.NS",

    "LT.NS",
    "AXISBANK.NS",
    "ASIANPAINT.NS",
    "MARUTI.NS",
    "SUNPHARMA.NS",
    "TITAN.NS",
    "ULTRACEMCO.NS",
    "NESTLEIND.NS",
    "BAJFINANCE.NS",
    "HCLTECH.NS",

    "WIPRO.NS",
    "TECHM.NS",
    "POWERGRID.NS",
    "NTPC.NS",
    "ONGC.NS",
    "TATASTEEL.NS",
    "JSWSTEEL.NS",
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "COALINDIA.NS",

    "TATAMOTORS.NS",
    "M&M.NS",
    "EICHERMOT.NS",
    "HEROMOTOCO.NS",
    "BAJAJ-AUTO.NS",
    "BAJAJFINSV.NS",
    "DRREDDY.NS",
    "CIPLA.NS",
    "DIVISLAB.NS",
    "APOLLOHOSP.NS",

    "BPCL.NS",
    "IOC.NS",
    "GRASIM.NS",
    "BRITANNIA.NS",
    "TATACONSUM.NS",
    "INDUSINDBK.NS",
    "HINDALCO.NS",
    "SHRIRAMFIN.NS",
    "BEL.NS",
    "TRENT.NS"
]

print("Number of stocks:", len(stocks))

print("pandas:", pd.__version__)
print("numpy:", np.__version__)
print("yfinance:", yf.__version__)
print("torch:", torch.__version__)
# print("PyG:", torch_geometric.__version__)
print("CUDA available:", torch.cuda.is_available())

raw_data = yf.download(
    tickers=stocks,
    period='2y',
    interval="1d",
    auto_adjust=True,
    group_by="column",
    progress=True,
    threads=True
    )
print(raw_data.shape)
raw_data.tail(10)

Number of stocks: 50
pandas: 3.0.5
numpy: 2.2.6
yfinance: 1.7.0
torch: 2.13.0+cpu
CUDA available: False

[**********************94%********************   ]  47 of 50 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}
$TATAMOTORS.NS: No data found, symbol may be delisted
[*********************100%***********************]  50 of 50 completed

1 Failed download:
['TATAMOTORS.NS']: No data found, symbol may be delisted

(501, 251)

Price          Adj Close        Close                              \
Ticker     TATAMOTORS.NS  ADANIENT.NS ADANIPORTS.NS APOLLOHOSP.NS
Date
2026-08-31           NaN  2859.100098   1593.099976        8898.5
2026-09-01           NaN  2863.899902   1647.500000        8755.0
2026-09-02           NaN  2891.800049   1672.699951        8719.0
2026-09-03           NaN  2901.000000   1706.500000        8692.0
2026-09-04           NaN  2938.000000   1707.300049        8650.0
2026-09-07           NaN  2950.000000           NaN           NaN
2026-09-08           NaN  2953.100098   1710.000000        8837.5
2026-09-09           NaN  3104.699951   1775.000000        8967.0
2026-09-10           NaN  3077.199951   1768.000000        8900.0
2026-09-11           NaN  3060.000000   1764.599976        8836.0

Price                                                              \
Ticker     ASIANPAINT.NS  AXISBANK.NS BAJAJ-AUTO.NS BAJAJFINSV.NS
Date
2026-08-31   2653.600098  1300.000000       12130.0   2021.000000
2026-09-01   2575.500000  1258.000000       12361.0   1972.000000
2026-09-02   2527.500000  1253.900024       12130.0   1990.000000
2026-09-03   2541.600098  1267.000000       11920.0   1992.099976
2026-09-04   2527.300049  1273.000000       11919.0   1970.000000
2026-09-07   2500.899902          NaN       11800.0   1938.599976
2026-09-08   2481.600098  1244.900024       11880.0   1938.099976
2026-09-09   2489.000000  1238.500000       11790.0   1927.000000
2026-09-10   2498.100098  1246.000000       11768.0   1940.500000
2026-09-11   2472.500000  1246.000000       11678.0   1913.500000

Price                                 ...       Volume                \
Ticker     BAJFINANCE.NS      BEL.NS  ... SUNPHARMA.NS TATACONSUM.NS
Date                                  ...
2026-08-31   1057.000000  414.450012  ...      2413221       1686812
2026-09-01   1053.900024  411.200012  ...      3595272       1005860
2026-09-02   1055.900024  405.750000  ...      1245419       1052859
2026-09-03   1049.000000  408.600006  ...      1205188        935640
2026-09-04   1060.500000  405.350006  ...       761333       1030689
2026-09-07   1060.000000  404.000000  ...      1579345       1368015
2026-09-08   1054.099976  410.549988  ...      1422627        720871
2026-09-09   1039.300049  406.000000  ...      1396896        973918
2026-09-10   1043.500000  405.000000  ...      1178648       1001929
2026-09-11   1034.500000  404.350006  ...      1445071        905959

Price                                                                      \
Ticker     TATAMOTORS.NS TATASTEEL.NS   TCS.NS TECHM.NS TITAN.NS TRENT.NS
Date
2026-08-31           NaN     36802869  2905846  2975369   630695   976926
2026-09-01           NaN     46663321  2678034  2412137   466855   652244
2026-09-02           NaN     19496175  2533005  1508528   812660   873641
2026-09-03           NaN     21964971  1892786  1647483   571600   520969
2026-09-04           NaN     36500951  2564322  1173518   310845   577393
2026-09-07           NaN     23695657  2297551  2028588   480336  1021019
2026-09-08           NaN     24272812  2148114  1575629   432671   588825
2026-09-09           NaN     45985325  3370071  1329200   502050   601991
2026-09-10           NaN     23334612  2490912  1405653   336565   503802
2026-09-11           NaN     31510206  2634124  2007328   403235   677898

Price
Ticker     ULTRACEMCO.NS  WIPRO.NS
Date
2026-08-31        381057  16666567
2026-09-01        168152   6813425
2026-09-02        228820  12056634
2026-09-03        247711   6496396
2026-09-04        280870   6882678
2026-09-07        214788  10720636
2026-09-08        338272   6948945
2026-09-09        325637  12001620
2026-09-10        270894   9586645
2026-09-11        223277   8484897

[10 rows x 251 columns]

In [3]:
raw_data.tail(10)

Price          Adj Close        Close                              \
Ticker     TATAMOTORS.NS  ADANIENT.NS ADANIPORTS.NS APOLLOHOSP.NS
Date
2026-08-31           NaN  2859.100098   1593.099976        8898.5
2026-09-01           NaN  2863.899902   1647.500000        8755.0
2026-09-02           NaN  2891.800049   1672.699951        8719.0
2026-09-03           NaN  2901.000000   1706.500000        8692.0
2026-09-04           NaN  2938.000000   1707.300049        8650.0
2026-09-07           NaN  2950.000000           NaN           NaN
2026-09-08           NaN  2953.100098   1710.000000        8837.5
2026-09-09           NaN  3104.699951   1775.000000        8967.0
2026-09-10           NaN  3077.199951   1768.000000        8900.0
2026-09-11           NaN  3060.000000   1764.599976        8836.0

Price                                                              \
Ticker     ASIANPAINT.NS  AXISBANK.NS BAJAJ-AUTO.NS BAJAJFINSV.NS
Date
2026-08-31   2653.600098  1300.000000       12130.0   2021.000000
2026-09-01   2575.500000  1258.000000       12361.0   1972.000000
2026-09-02   2527.500000  1253.900024       12130.0   1990.000000
2026-09-03   2541.600098  1267.000000       11920.0   1992.099976
2026-09-04   2527.300049  1273.000000       11919.0   1970.000000
2026-09-07   2500.899902          NaN       11800.0   1938.599976
2026-09-08   2481.600098  1244.900024       11880.0   1938.099976
2026-09-09   2489.000000  1238.500000       11790.0   1927.000000
2026-09-10   2498.100098  1246.000000       11768.0   1940.500000
2026-09-11   2472.500000  1246.000000       11678.0   1913.500000

Price                                 ...       Volume                \
Ticker     BAJFINANCE.NS      BEL.NS  ... SUNPHARMA.NS TATACONSUM.NS
Date                                  ...
2026-08-31   1057.000000  414.450012  ...      2413221       1686812
2026-09-01   1053.900024  411.200012  ...      3595272       1005860
2026-09-02   1055.900024  405.750000  ...      1245419       1052859
2026-09-03   1049.000000  408.600006  ...      1205188        935640
2026-09-04   1060.500000  405.350006  ...       761333       1030689
2026-09-07   1060.000000  404.000000  ...      1579345       1368015
2026-09-08   1054.099976  410.549988  ...      1422627        720871
2026-09-09   1039.300049  406.000000  ...      1396896        973918
2026-09-10   1043.500000  405.000000  ...      1178648       1001929
2026-09-11   1034.500000  404.350006  ...      1445071        905959

Price                                                                      \
Ticker     TATAMOTORS.NS TATASTEEL.NS   TCS.NS TECHM.NS TITAN.NS TRENT.NS
Date
2026-08-31           NaN     36802869  2905846  2975369   630695   976926
2026-09-01           NaN     46663321  2678034  2412137   466855   652244
2026-09-02           NaN     19496175  2533005  1508528   812660   873641
2026-09-03           NaN     21964971  1892786  1647483   571600   520969
2026-09-04           NaN     36500951  2564322  1173518   310845   577393
2026-09-07           NaN     23695657  2297551  2028588   480336  1021019
2026-09-08           NaN     24272812  2148114  1575629   432671   588825
2026-09-09           NaN     45985325  3370071  1329200   502050   601991
2026-09-10           NaN     23334612  2490912  1405653   336565   503802
2026-09-11           NaN     31510206  2634124  2007328   403235   677898

Price
Ticker     ULTRACEMCO.NS  WIPRO.NS
Date
2026-08-31        381057  16666567
2026-09-01        168152   6813425
2026-09-02        228820  12056634
2026-09-03        247711   6496396
2026-09-04        280870   6882678
2026-09-07        214788  10720636
2026-09-08        338272   6948945
2026-09-09        325637  12001620
2026-09-10        270894   9586645
2026-09-11        223277   8484897

[10 rows x 251 columns]

In [4]:

date_df = raw_data.loc["2026-09-10"].unstack(level='Ticker')
print(date_df.shape)

date_df
print(date_df.isna().sum())
print(date_df.dropna(axis=0))

date_df=date_df.drop('Adj Close')
date_df

(6, 50)
Ticker
ADANIENT.NS      1
ADANIPORTS.NS    1
APOLLOHOSP.NS    1
ASIANPAINT.NS    1
AXISBANK.NS      1
BAJAJ-AUTO.NS    1
BAJAJFINSV.NS    1
BAJFINANCE.NS    1
BEL.NS           1
BHARTIARTL.NS    1
BPCL.NS          1
BRITANNIA.NS     1
CIPLA.NS         1
COALINDIA.NS     1
DIVISLAB.NS      1
DRREDDY.NS       1
EICHERMOT.NS     1
GRASIM.NS        1
HCLTECH.NS       1
HDFCBANK.NS      1
HEROMOTOCO.NS    1
HINDALCO.NS      1
HINDUNILVR.NS    1
ICICIBANK.NS     1
INDUSINDBK.NS    1
INFY.NS          1
IOC.NS           1
ITC.NS           1
JSWSTEEL.NS      1
KOTAKBANK.NS     1
LT.NS            1
M&M.NS           1
MARUTI.NS        1
NESTLEIND.NS     1
NTPC.NS          1
ONGC.NS          1
POWERGRID.NS     1
RELIANCE.NS      1
SBIN.NS          1
SHRIRAMFIN.NS    1
SUNPHARMA.NS     1
TATACONSUM.NS    1
TATAMOTORS.NS    6
TATASTEEL.NS     1
TCS.NS           1
TECHM.NS         1
TITAN.NS         1
TRENT.NS         1
ULTRACEMCO.NS    1
WIPRO.NS         1
dtype: int64
Empty DataFrame
Columns: [ADANIENT.NS, ADANIPORTS.NS, APOLLOHOSP.NS, ASIANPAINT.NS, AXISBANK.NS, BAJAJ-AUTO.NS, BAJAJFINSV.NS, BAJFINANCE.NS, BEL.NS, BHARTIARTL.NS, BPCL.NS, BRITANNIA.NS, CIPLA.NS, COALINDIA.NS, DIVISLAB.NS, DRREDDY.NS, EICHERMOT.NS, GRASIM.NS, HCLTECH.NS, HDFCBANK.NS, HEROMOTOCO.NS, HINDALCO.NS, HINDUNILVR.NS, ICICIBANK.NS, INDUSINDBK.NS, INFY.NS, IOC.NS, ITC.NS, JSWSTEEL.NS, KOTAKBANK.NS, LT.NS, M&M.NS, MARUTI.NS, NESTLEIND.NS, NTPC.NS, ONGC.NS, POWERGRID.NS, RELIANCE.NS, SBIN.NS, SHRIRAMFIN.NS, SUNPHARMA.NS, TATACONSUM.NS, TATAMOTORS.NS, TATASTEEL.NS, TCS.NS, TECHM.NS, TITAN.NS, TRENT.NS, ULTRACEMCO.NS, WIPRO.NS]
Index: []

[0 rows x 50 columns]

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,TRENT.NS,ULTRACEMCO.NS,WIPRO.NS
Price,,,,,,,,,,,,,,,,,,,,,
Close,3.077200e+03,1.768000e+03,8900.0,2498.100098,1.246000e+03,11768.0,1940.500000,1.043500e+03,4.050000e+02,1.839000e+03,...,1.861000e+03,9.996000e+02,NaN,1.867800e+02,2.204100e+03,1.525800e+03,5021.0,2818.699951,10979.0,1.663000e+02
High,3.114500e+03,1.780000e+03,9024.0,2498.100098,1.255200e+03,11820.0,1942.699951,1.048700e+03,4.072000e+02,1.849000e+03,...,1.875300e+03,1.005600e+03,NaN,1.890000e+02,2.232000e+03,1.544700e+03,5021.0,2835.000000,10979.0,1.691900e+02
Low,3.041100e+03,1.750400e+03,8875.0,2468.600098,1.240400e+03,11673.0,1921.099976,1.036500e+03,4.020000e+02,1.814000e+03,...,1.840500e+03,9.925000e+02,NaN,1.850000e+02,2.190600e+03,1.498100e+03,4974.5,2800.000000,10858.0,1.660000e+02
Open,3.114500e+03,1.779900e+03,9000.0,2485.100098,1.242100e+03,11771.0,1932.900024,1.042500e+03,4.070000e+02,1.815100e+03,...,1.865900e+03,1.004000e+03,NaN,1.890000e+02,2.199000e+03,1.511900e+03,5000.5,2811.000000,10896.0,1.679000e+02
Volume,1.716315e+06,2.777377e+06,329159.0,549332.000000,4.150654e+06,121394.0,658197.000000,3.902988e+06,8.716895e+06,4.588126e+06,...,1.178648e+06,1.001929e+06,NaN,2.333461e+07,2.490912e+06,1.405653e+06,336565.0,503802.000000,270894.0,9.586645e+06

In [5]:
date_df.index

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='str', name='Price')

In [6]:
print(date_df.loc['Close'].size)
date_df.loc['Close']

50

Ticker
ADANIENT.NS       3077.199951
ADANIPORTS.NS     1768.000000
APOLLOHOSP.NS     8900.000000
ASIANPAINT.NS     2498.100098
AXISBANK.NS       1246.000000
BAJAJ-AUTO.NS    11768.000000
BAJAJFINSV.NS     1940.500000
BAJFINANCE.NS     1043.500000
BEL.NS             405.000000
BHARTIARTL.NS     1839.000000
BPCL.NS            303.000000
BRITANNIA.NS      5009.000000
CIPLA.NS          1373.300049
COALINDIA.NS       432.000000
DIVISLAB.NS       9438.500000
DRREDDY.NS        1143.000000
EICHERMOT.NS      7697.000000
GRASIM.NS         3319.000000
HCLTECH.NS        1207.000000
HDFCBANK.NS        693.799988
HEROMOTOCO.NS     5280.000000
HINDALCO.NS       1014.000000
HINDUNILVR.NS     1942.300049
ICICIBANK.NS      1384.500000
INDUSINDBK.NS      993.299988
INFY.NS           1036.500000
IOC.NS             134.940002
ITC.NS             259.299988
JSWSTEEL.NS       1304.000000
KOTAKBANK.NS       416.549988
LT.NS             3955.000000
M&M.NS            3123.800049
MARUTI.NS        12590.000000
NESTLEIND.NS      1386.199951
NTPC.NS            335.000000
ONGC.NS            237.270004
POWERGRID.NS       271.750000
RELIANCE.NS       1274.000000
SBIN.NS           1009.700012
SHRIRAMFIN.NS     1038.000000
SUNPHARMA.NS      1861.000000
TATACONSUM.NS      999.599976
TATAMOTORS.NS             NaN
TATASTEEL.NS       186.779999
TCS.NS            2204.100098
TECHM.NS          1525.800049
TITAN.NS          5021.000000
TRENT.NS          2818.699951
ULTRACEMCO.NS    10979.000000
WIPRO.NS           166.300003
Name: Close, dtype: float64

In [7]:
date_df.loc[ 'High']

Ticker
ADANIENT.NS       3114.500000
ADANIPORTS.NS     1780.000000
APOLLOHOSP.NS     9024.000000
ASIANPAINT.NS     2498.100098
AXISBANK.NS       1255.199951
BAJAJ-AUTO.NS    11820.000000
BAJAJFINSV.NS     1942.699951
BAJFINANCE.NS     1048.699951
BEL.NS             407.200012
BHARTIARTL.NS     1849.000000
BPCL.NS            306.100006
BRITANNIA.NS      5108.000000
CIPLA.NS          1380.000000
COALINDIA.NS       436.299988
DIVISLAB.NS       9604.000000
DRREDDY.NS        1147.199951
EICHERMOT.NS      7746.000000
GRASIM.NS         3324.399902
HCLTECH.NS        1237.000000
HDFCBANK.NS        694.500000
HEROMOTOCO.NS     5280.000000
HINDALCO.NS       1029.500000
HINDUNILVR.NS     1950.000000
ICICIBANK.NS      1393.000000
INDUSINDBK.NS     1002.700012
INFY.NS           1046.599976
IOC.NS             136.149994
ITC.NS             263.899994
JSWSTEEL.NS       1311.300049
KOTAKBANK.NS       416.549988
LT.NS             3965.500000
M&M.NS            3146.899902
MARUTI.NS        12693.000000
NESTLEIND.NS      1402.800049
NTPC.NS            335.700012
ONGC.NS            239.800003
POWERGRID.NS       271.750000
RELIANCE.NS       1285.300049
SBIN.NS           1011.900024
SHRIRAMFIN.NS     1039.000000
SUNPHARMA.NS      1875.300049
TATACONSUM.NS     1005.599976
TATAMOTORS.NS             NaN
TATASTEEL.NS       189.000000
TCS.NS            2232.000000
TECHM.NS          1544.699951
TITAN.NS          5021.000000
TRENT.NS          2835.000000
ULTRACEMCO.NS    10979.000000
WIPRO.NS           169.190002
Name: High, dtype: float64

In [8]:
date_df.loc['Close', 'ADANIENT.NS']

np.float64(3077.199951171875)

In [9]:
date_df.iloc[4]# volume

Ticker
ADANIENT.NS       1716315.0
ADANIPORTS.NS     2777377.0
APOLLOHOSP.NS      329159.0
ASIANPAINT.NS      549332.0
AXISBANK.NS       4150654.0
BAJAJ-AUTO.NS      121394.0
BAJAJFINSV.NS      658197.0
BAJFINANCE.NS     3902988.0
BEL.NS            8716895.0
BHARTIARTL.NS     4588126.0
BPCL.NS           3231631.0
BRITANNIA.NS       263129.0
CIPLA.NS           826221.0
COALINDIA.NS      8811171.0
DIVISLAB.NS        338181.0
DRREDDY.NS        1684792.0
EICHERMOT.NS       289058.0
GRASIM.NS         1056285.0
HCLTECH.NS        2197859.0
HDFCBANK.NS      27108053.0
HEROMOTOCO.NS      501164.0
HINDALCO.NS       2172772.0
HINDUNILVR.NS     1232506.0
ICICIBANK.NS     10580641.0
INDUSINDBK.NS      972483.0
INFY.NS           8998529.0
IOC.NS            6629384.0
ITC.NS           17541602.0
JSWSTEEL.NS       1102536.0
KOTAKBANK.NS      7755254.0
LT.NS             1376951.0
M&M.NS            2140618.0
MARUTI.NS          338613.0
NESTLEIND.NS       568997.0
NTPC.NS           6905905.0
ONGC.NS          12771340.0
POWERGRID.NS     12187656.0
RELIANCE.NS       9296079.0
SBIN.NS           5504031.0
SHRIRAMFIN.NS     2757241.0
SUNPHARMA.NS      1178648.0
TATACONSUM.NS     1001929.0
TATAMOTORS.NS           NaN
TATASTEEL.NS     23334612.0
TCS.NS            2490912.0
TECHM.NS          1405653.0
TITAN.NS           336565.0
TRENT.NS           503802.0
ULTRACEMCO.NS      270894.0
WIPRO.NS          9586645.0
Name: Volume, dtype: float64

In [10]:
date_df

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,TRENT.NS,ULTRACEMCO.NS,WIPRO.NS
Price,,,,,,,,,,,,,,,,,,,,,
Close,3.077200e+03,1.768000e+03,8900.0,2498.100098,1.246000e+03,11768.0,1940.500000,1.043500e+03,4.050000e+02,1.839000e+03,...,1.861000e+03,9.996000e+02,NaN,1.867800e+02,2.204100e+03,1.525800e+03,5021.0,2818.699951,10979.0,1.663000e+02
High,3.114500e+03,1.780000e+03,9024.0,2498.100098,1.255200e+03,11820.0,1942.699951,1.048700e+03,4.072000e+02,1.849000e+03,...,1.875300e+03,1.005600e+03,NaN,1.890000e+02,2.232000e+03,1.544700e+03,5021.0,2835.000000,10979.0,1.691900e+02
Low,3.041100e+03,1.750400e+03,8875.0,2468.600098,1.240400e+03,11673.0,1921.099976,1.036500e+03,4.020000e+02,1.814000e+03,...,1.840500e+03,9.925000e+02,NaN,1.850000e+02,2.190600e+03,1.498100e+03,4974.5,2800.000000,10858.0,1.660000e+02
Open,3.114500e+03,1.779900e+03,9000.0,2485.100098,1.242100e+03,11771.0,1932.900024,1.042500e+03,4.070000e+02,1.815100e+03,...,1.865900e+03,1.004000e+03,NaN,1.890000e+02,2.199000e+03,1.511900e+03,5000.5,2811.000000,10896.0,1.679000e+02
Volume,1.716315e+06,2.777377e+06,329159.0,549332.000000,4.150654e+06,121394.0,658197.000000,3.902988e+06,8.716895e+06,4.588126e+06,...,1.178648e+06,1.001929e+06,NaN,2.333461e+07,2.490912e+06,1.405653e+06,336565.0,503802.000000,270894.0,9.586645e+06

In [11]:
raw_data.tail(10)
# print(raw_data.tail(10))
date_df
print(raw_data.isna().sum())
print(raw_data.dropna(axis=0))

Price      Ticker
Adj Close  TATAMOTORS.NS    501
Close      ADANIENT.NS        0
           ADANIPORTS.NS      1
           APOLLOHOSP.NS      1
           ASIANPAINT.NS      0
                           ...
Volume     TECHM.NS           0
           TITAN.NS           0
           TRENT.NS           0
           ULTRACEMCO.NS      0
           WIPRO.NS           0
Length: 251, dtype: int64
Empty DataFrame
Columns: [(Adj Close, TATAMOTORS.NS), (Close, ADANIENT.NS), (Close, ADANIPORTS.NS), (Close, APOLLOHOSP.NS), (Close, ASIANPAINT.NS), (Close, AXISBANK.NS), (Close, BAJAJ-AUTO.NS), (Close, BAJAJFINSV.NS), (Close, BAJFINANCE.NS), (Close, BEL.NS), (Close, BHARTIARTL.NS), (Close, BPCL.NS), (Close, BRITANNIA.NS), (Close, CIPLA.NS), (Close, COALINDIA.NS), (Close, DIVISLAB.NS), (Close, DRREDDY.NS), (Close, EICHERMOT.NS), (Close, GRASIM.NS), (Close, HCLTECH.NS), (Close, HDFCBANK.NS), (Close, HEROMOTOCO.NS), (Close, HINDALCO.NS), (Close, HINDUNILVR.NS), (Close, ICICIBANK.NS), (Close, INDUSINDBK.NS), (Close, INFY.NS), (Close, IOC.NS), (Close, ITC.NS), (Close, JSWSTEEL.NS), (Close, KOTAKBANK.NS), (Close, LT.NS), (Close, M&M.NS), (Close, MARUTI.NS), (Close, NESTLEIND.NS), (Close, NTPC.NS), (Close, ONGC.NS), (Close, POWERGRID.NS), (Close, RELIANCE.NS), (Close, SBIN.NS), (Close, SHRIRAMFIN.NS), (Close, SUNPHARMA.NS), (Close, TATACONSUM.NS), (Close, TATAMOTORS.NS), (Close, TATASTEEL.NS), (Close, TCS.NS), (Close, TECHM.NS), (Close, TITAN.NS), (Close, TRENT.NS), (Close, ULTRACEMCO.NS), (Close, WIPRO.NS), (High, ADANIENT.NS), (High, ADANIPORTS.NS), (High, APOLLOHOSP.NS), (High, ASIANPAINT.NS), (High, AXISBANK.NS), (High, BAJAJ-AUTO.NS), (High, BAJAJFINSV.NS), (High, BAJFINANCE.NS), (High, BEL.NS), (High, BHARTIARTL.NS), (High, BPCL.NS), (High, BRITANNIA.NS), (High, CIPLA.NS), (High, COALINDIA.NS), (High, DIVISLAB.NS), (High, DRREDDY.NS), (High, EICHERMOT.NS), (High, GRASIM.NS), (High, HCLTECH.NS), (High, HDFCBANK.NS), (High, HEROMOTOCO.NS), (High, HINDALCO.NS), (High, HINDUNILVR.NS), (High, ICICIBANK.NS), (High, INDUSINDBK.NS), (High, INFY.NS), (High, IOC.NS), (High, ITC.NS), (High, JSWSTEEL.NS), (High, KOTAKBANK.NS), (High, LT.NS), (High, M&M.NS), (High, MARUTI.NS), (High, NESTLEIND.NS), (High, NTPC.NS), (High, ONGC.NS), (High, POWERGRID.NS), (High, RELIANCE.NS), (High, SBIN.NS), (High, SHRIRAMFIN.NS), (High, SUNPHARMA.NS), (High, TATACONSUM.NS), (High, TATAMOTORS.NS), (High, TATASTEEL.NS), (High, TCS.NS), (High, TECHM.NS), (High, TITAN.NS), (High, TRENT.NS), (High, ULTRACEMCO.NS), ...]
Index: []

[0 rows x 251 columns]

In [12]:
close_df = raw_data['Close']
close_df
volume = raw_data['Volume']
volume
high = raw_data['High'] 
low = raw_data['Low']
opening = raw_data['Open']
opening

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,TRENT.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2024-09-11,2982.187509,1441.829116,6864.331370,3245.804047,1185.272017,10644.381057,1826.550723,716.151529,282.624365,1545.907988,...,1802.942264,1190.921785,NaN,143.524025,4200.701435,1513.395223,3708.533586,7146.258378,11267.142882,243.289126
2024-09-12,2947.220515,1430.977888,6907.109234,3299.655970,1188.167390,11041.583625,1848.221622,732.943968,287.014926,1563.243141,...,1821.350687,1191.020184,NaN,145.534718,4190.295115,1520.811847,3712.608274,7183.232189,11206.618376,241.180629
2024-09-13,2969.199686,1459.666833,7059.517719,3285.507506,1207.935234,11275.047551,1872.289376,733.763879,289.086922,1616.962387,...,1831.021231,1206.769113,NaN,146.281543,4208.644978,1548.976900,3753.351451,7233.628174,11388.871253,247.367098
2024-09-16,2969.199898,1441.977806,6988.685658,3289.864733,1220.015551,11285.145361,1899.452994,758.626659,287.014959,1600.753527,...,1828.075901,1200.863312,NaN,148.407117,4205.857102,1550.103480,3744.407858,7255.084010,11369.394425,256.264544
2024-09-17,2987.232834,1429.788844,6995.052147,3266.170055,1233.194185,11233.211693,1856.510499,724.794732,286.620292,1615.982965,...,1829.057578,1203.816239,NaN,147.449657,4193.082924,1548.131937,3736.358239,7399.786850,11298.841093,254.410912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-07,2940.000000,NaN,NaN,2511.100098,NaN,11810.000000,1968.000000,1064.000000,406.350006,1845.000000,...,1899.000000,1014.000000,NaN,189.000000,2290.100098,1575.099976,5010.000000,2850.000000,11370.000000,175.889999
2026-09-08,2933.000000,1694.000000,8761.500000,2499.000000,1262.800049,11727.000000,1938.599976,1058.800049,408.000000,1846.199951,...,1892.000000,1015.000000,NaN,185.899994,2270.000000,1556.099976,4975.000000,2800.500000,11175.000000,172.800003
2026-09-09,2959.899902,1719.000000,8825.000000,2459.100098,1236.000000,11841.000000,1939.099976,1045.099976,411.549988,1830.500000,...,1892.599976,1010.799988,NaN,184.800003,2237.000000,1531.000000,5010.000000,2793.600098,10975.000000,168.699997
2026-09-10,3114.500000,1779.900024,9000.000000,2485.100098,1242.099976,11771.000000,1932.900024,1042.500000,407.000000,1815.099976,...,1865.900024,1004.000000,NaN,189.000000,2199.000000,1511.900024,5000.500000,2811.000000,10896.000000,167.899994
2026-09-11,3040.000000,1755.000000,8806.000000,2453.199951,1237.900024,11624.000000,1912.099976,1031.000000,402.600006,1832.000000,...,1845.000000,993.000000,NaN,184.000000,2185.500000,1519.300049,4964.000000,2789.000000,10859.000000,165.199997

In [13]:
close_df = close_df.dropna(axis=1,how='all')
close_df = close_df.dropna(axis=0,how='any')
volume = volume[close_df.columns]
volume = volume.dropna(axis=0,how='any')
high = high[close_df.columns]
high = high.dropna(axis=0,how='any')
low = low[close_df.columns]
low = low.dropna(axis=0,how='any')
opening = opening[close_df.columns]
opening = opening.dropna(axis=0,how='any')
opening

Ticker,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BEL.NS,BHARTIARTL.NS,...,SHRIRAMFIN.NS,SUNPHARMA.NS,TATACONSUM.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,TRENT.NS,ULTRACEMCO.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2024-09-11,2982.187509,1441.829116,6864.331370,3245.804047,1185.272017,10644.381057,1826.550723,716.151529,282.624365,1545.907988,...,635.122553,1802.942264,1190.921785,143.524025,4200.701435,1513.395223,3708.533586,7146.258378,11267.142882,243.289126
2024-09-12,2947.220515,1430.977888,6907.109234,3299.655970,1188.167390,11041.583625,1848.221622,732.943968,287.014926,1563.243141,...,641.920918,1821.350687,1191.020184,145.534718,4190.295115,1520.811847,3712.608274,7183.232189,11206.618376,241.180629
2024-09-13,2969.199686,1459.666833,7059.517719,3285.507506,1207.935234,11275.047551,1872.289376,733.763879,289.086922,1616.962387,...,661.314762,1831.021231,1206.769113,146.281543,4208.644978,1548.976900,3753.351451,7233.628174,11388.871253,247.367098
2024-09-16,2969.199898,1441.977806,6988.685658,3289.864733,1220.015551,11285.145361,1899.452994,758.626659,287.014959,1600.753527,...,657.093728,1828.075901,1200.863312,148.407117,4205.857102,1550.103480,3744.407858,7255.084010,11369.394425,256.264544
2024-09-17,2987.232834,1429.788844,6995.052147,3266.170055,1233.194185,11233.211693,1856.510499,724.794732,286.620292,1615.982965,...,664.290996,1829.057578,1203.816239,147.449657,4193.082924,1548.131937,3736.358239,7399.786850,11298.841093,254.410912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,2900.000000,1699.900024,8702.500000,2540.000000,1270.300049,12005.000000,1985.000000,1050.599976,409.250000,1868.099976,...,1044.199951,1912.000000,1020.000000,184.199997,2330.000000,1605.099976,5010.000000,2849.000000,11357.000000,176.740005
2026-09-08,2933.000000,1694.000000,8761.500000,2499.000000,1262.800049,11727.000000,1938.599976,1058.800049,408.000000,1846.199951,...,1030.000000,1892.000000,1015.000000,185.899994,2270.000000,1556.099976,4975.000000,2800.500000,11175.000000,172.800003
2026-09-09,2959.899902,1719.000000,8825.000000,2459.100098,1236.000000,11841.000000,1939.099976,1045.099976,411.549988,1830.500000,...,1018.200012,1892.599976,1010.799988,184.800003,2237.000000,1531.000000,5010.000000,2793.600098,10975.000000,168.699997
2026-09-10,3114.500000,1779.900024,9000.000000,2485.100098,1242.099976,11771.000000,1932.900024,1042.500000,407.000000,1815.099976,...,1030.000000,1865.900024,1004.000000,189.000000,2199.000000,1511.900024,5000.500000,2811.000000,10896.000000,167.899994
2026-09-11,3040.000000,1755.000000,8806.000000,2453.199951,1237.900024,11624.000000,1912.099976,1031.000000,402.600006,1832.000000,...,1021.000000,1845.000000,993.000000,184.000000,2185.500000,1519.300049,4964.000000,2789.000000,10859.000000,165.199997

In [14]:
# 1. Daily return
r1 = close_df.pct_change()
r5 = close_df.pct_change(5)
r20 = close_df.pct_change(20)


# 3. Volume change
volume_change = volume.rolling(window=20).mean()

# 4. Open-Close return
open_close_return = (close_df - opening) / opening

# 5. Rolling volatility
volatility = r1.rolling(window=20).std()

#6. M20 ratio
M20Ratio = close_df.rolling(window=20).mean()/close_df

# Target
nxt_day_return = r1.shift(-1) 
target = (nxt_day_return > 0).astype(int)

# concatinaation
features_df = pd.concat(
    {

        'R1': r1,
        'R5': r5,
        'R20': r20,
        'M20Ratio': M20Ratio,
        'VolumeChange': volume_change,
        'Volatility': volatility,
        'OpenCloseReturn': open_close_return,
        'Target':target
    },
    axis=1
)
print(close_df.shape)
# 1. Drop rows with missing values
features_df = features_df.dropna()

# 2. Extract your specific date slice and unstack it
date_df = features_df.loc['2026-09-10'].unstack(level='Ticker').T

# 🚀 THE ULTIMATE FIX: Force the 'Target' row to be display-integers directly on the final view
# date_df.loc['Target'] = date_df.loc['Target'].astype(int)
date_df['Target'] = date_df['Target'].astype(int).astype(str)

# View the result
date_df

(499, 49)

,R1,R5,R20,M20Ratio,VolumeChange,Volatility,OpenCloseReturn,Target
Ticker,,,,,,,,
ADANIENT.NS,-0.008858,0.064112,0.030646,0.977169,2128938.60,0.028009,-0.011976,0
ADANIPORTS.NS,-0.003944,0.056974,0.061862,0.958066,2518663.10,0.021979,-0.006686,0
APOLLOHOSP.NS,-0.007472,0.020759,0.036450,0.987337,361848.05,0.013360,-0.011111,0
ASIANPAINT.NS,0.003656,-0.011632,-0.088285,1.042887,578889.50,0.011775,0.005231,0
AXISBANK.NS,0.006056,-0.006300,0.013008,1.001990,4675793.80,0.013341,0.003140,0
BAJAJ-AUTO.NS,-0.001866,-0.029843,0.005812,1.005897,225196.80,0.011363,-0.000255,0
BAJAJFINSV.NS,0.007006,-0.024874,-0.039594,1.027812,649512.45,0.009084,0.003932,0
BAJFINANCE.NS,0.004041,-0.011744,-0.046335,1.028131,4623486.90,0.009023,0.000959,0
BEL.NS,-0.002463,-0.001848,-0.000370,1.012012,10095982.65,0.009298,-0.004914,0
BHARTIARTL.NS,0.013391,-0.012776,-0.054499,1.031751,6465902.05,0.016898,0.013167,0
BPCL.NS,-0.001812,-0.051940,-0.044164,1.036436,5126402.90,0.013565,0.000165,1
BRITANNIA.NS,-0.015914,-0.028133,-0.112745,1.059598,271138.60,0.010551,-0.019381,0
CIPLA.NS,0.007483,-0.027959,-0.061312,1.030904,729690.95,0.008650,0.004756,0
COALINDIA.NS,0.002320,0.046949,0.068819,0.939201,10697627.40,0.012276,-0.002309,0
DIVISLAB.NS,-0.005217,0.023698,0.097500,0.948464,430098.35,0.019267,-0.016874,0
DRREDDY.NS,-0.001747,-0.011673,-0.047500,1.025761,1232221.95,0.008417,0.002632,1
EICHERMOT.NS,-0.004848,-0.001880,-0.043732,1.030973,407812.80,0.009533,-0.002074,0
GRASIM.NS,0.005758,0.007314,0.003386,0.992273,1138303.90,0.009759,0.008815,0
HCLTECH.NS,-0.018540,-0.093504,-0.116010,1.083447,1966360.90,0.017409,-0.014533,0
HDFCBANK.NS,0.009751,-0.009989,-0.048285,1.031663,27062262.15,0.010648,0.009751,1
HEROMOTOCO.NS,0.011882,-0.003774,-0.104326,1.052225,556963.85,0.014373,0.008596,0
HINDALCO.NS,-0.012562,0.004259,-0.059805,1.015999,3116925.55,0.014545,-0.013139,0
HINDUNILVR.NS,-0.001388,-0.016557,-0.058507,1.033754,1247469.15,0.009284,0.001186,0
ICICIBANK.NS,-0.003311,-0.029443,-0.032968,1.024312,9049493.15,0.009809,-0.001010,0
INDUSINDBK.NS,-0.010657,0.015644,-0.023784,1.013349,1178861.50,0.012425,-0.008584,0
INFY.NS,0.001449,-0.090789,-0.118697,1.083565,8036571.30,0.018613,-0.002982,1
IOC.NS,-0.004867,-0.015036,-0.031702,1.018512,7410583.85,0.010507,0.004691,1
ITC.NS,-0.005752,-0.026286,-0.061018,1.032260,14096215.80,0.015909,-0.006513,1
JSWSTEEL.NS,-0.004580,-0.001531,0.027500,1.000836,1652886.75,0.011651,0.002306,0
KOTAKBANK.NS,0.006159,-0.016411,0.066709,0.982511,11894713.50,0.012661,0.006889,1
LT.NS,0.008260,-0.006531,-0.016169,1.018745,1344223.65,0.008064,0.001418,0
M&M.NS,-0.008317,-0.020752,-0.082207,1.061600,1713364.75,0.009169,-0.005698,0
MARUTI.NS,-0.002219,-0.020157,-0.092613,1.058912,333732.50,0.011684,-0.007019,0
NESTLEIND.NS,-0.004882,-0.027228,-0.080159,1.046418,1418709.55,0.013143,-0.007589,0
NTPC.NS,0.001495,0.015152,-0.002449,0.991888,8447700.45,0.008761,-0.001937,0
ONGC.NS,0.013888,0.003283,-0.003223,0.990831,11380824.45,0.008534,0.004956,0
POWERGRID.NS,0.022193,0.018553,0.008536,0.981766,8673708.05,0.011413,0.022193,0
RELIANCE.NS,-0.003909,-0.029777,-0.041384,1.023183,10757809.85,0.010613,-0.003520,0
SBIN.NS,0.009195,-0.010971,-0.066821,1.030663,7141356.30,0.008853,0.007685,0
SHRIRAMFIN.NS,0.008746,-0.008596,-0.070891,1.050530,3601195.10,0.015542,0.007767,0
SUNPHARMA.NS,-0.002091,-0.036600,-0.042695,1.025325,1470834.80,0.013128,-0.002626,0
TATACONSUM.NS,-0.001399,-0.012253,-0.058668,1.043127,1099373.80,0.010387,-0.004382,0
TATASTEEL.NS,-0.010437,0.015937,0.003115,0.993104,27961316.65,0.012333,-0.011746,0
TCS.NS,-0.001766,-0.061286,-0.061965,1.045027,2423298.60,0.015507,0.002319,0
TECHM.NS,0.011804,-0.059889,-0.061046,1.045261,1984906.20,0.014864,0.009194,1
TITAN.NS,0.003197,-0.010445,-0.015297,1.009339,505803.20,0.006227,0.004100,0
TRENT.NS,-0.000461,-0.011780,-0.056344,1.027263,656401.50,0.009059,0.002739,0
ULTRACEMCO.NS,0.007248,-0.036338,-0.076697,1.042814,251863.85,0.011652,0.007617,1
WIPRO.NS,-0.004192,-0.060929,-0.095901,1.071771,8213064.50,0.014623,-0.009529,1

In [15]:

import os

# 1. Create the folder up in the root project directory
os.makedirs("../data/processed", exist_ok=True)

# 2. 🚀 THE FIX: Assign to a new variable name without using inplace=True
# This avoids the "already exists" error if you run the cell multiple times!
csv_ready_df = date_df.reset_index()

# 3. Save the new flat dataframe to your root folder CSV path
csv_ready_df.to_csv(
    "../data/processed/nifty50_features.csv",
    index=False,
)

print("Processed dataset successfully saved to the main root folder.")

Processed dataset successfully saved to the main root folder.